insert into public.org_notifications_types (
  key,
  category,
  visible_to_owner,
  visible_to_admin,
  visible_to_editor,
  default_in_app,
  default_email,
  title_template,
  body_template
) values
-- Billing
('org_subscription_started', 'billing', true, true, false, true, true,
 'Subscription activated',
 'Your organization is now subscribed to the {{tier_name}} plan at {{amount}}/{{interval}}.'),
('org_subscription_renewed', 'billing', true, true, false, true, true,
 'Subscription renewed',
 'Your {{tier_name}} subscription has been renewed. Next billing date: {{next_billing_date}}.'),
('org_subscription_failed', 'billing', true, true, false, true, true,
 'Payment failed',
 'We couldn''t process your payment for the {{tier_name}} plan. Please update your payment method.'),
('org_subscription_expiring', 'billing', true, true, false, true, true,
 'Subscription expiring soon',
 'Your {{tier_name}} subscription expires on {{expiry_date}}. Renew to keep access to premium features.'),
('org_payment_method_expiring', 'billing', true, true, false, true, true,
 'Payment method expiring',
 'Your payment method ending in {{last4}} expires on {{expiry_date}}. Please update it to avoid service interruption.'),
('org_invoice_ready', 'billing', true, true, false, true, true,
 'Invoice ready',
 'Your invoice for {{amount}} is ready. Download it from your billing dashboard.'),
('org_tier_upgraded', 'billing', true, true, true, true, false,
 'Plan upgraded! 🎉',
 'Your organization has been upgraded to {{tier_name}}. Enjoy your new features!'),
('org_tier_downgraded', 'billing', true, true, false, true, true,
 'Plan changed',
 'Your organization has been moved to the {{tier_name}} plan. Changes take effect on {{effective_date}}.'),
-- Members
('org_member_invited', 'members', true, true, false, true, false,
 'Member invited',
 '{{invited_by_name}} invited {{member_email}} to join as {{role}}.'),
('org_member_joined', 'members', true, true, true, true, false,
 'New member joined',
 '{{member_name}} has joined your organization as {{role}}.'),
('org_member_left', 'members', true, true, false, true, false,
 'Member left',
 '{{member_name}} has left your organization.'),
('org_member_role_changed', 'members', true, true, false, true, false,
 'Member role updated',
 '{{member_name}}''s role has been changed from {{old_role}} to {{new_role}} by {{changed_by_name}}.'),
('org_member_removed', 'members', true, true, false, true, false,
 'Member removed',
 '{{member_name}} was removed from the organization by {{removed_by_name}}.'),
('org_ownership_transferred', 'members', true, true, true, true, true,
 'Ownership transferred',
 'Organization ownership has been transferred from {{previous_owner_name}} to {{new_owner_name}}.'),
-- Content
('org_course_published', 'content', true, true, true, true, false,
 'Course published',
 '{{course_title}} has been published by {{published_by_name}}.'),
('org_course_milestone_reached', 'content', true, true, true, true, false,
 'Milestone reached! 🎯',
 '{{course_title}} has reached {{milestone_count}} {{milestone_type}}!'),
('org_content_flagged', 'content', true, true, false, true, true,
 'Content flagged for review',
 '{{content_type}} "{{content_title}}" has been flagged for {{reason}}. Please review.'),
-- Compliance
('org_verification_approved', 'compliance', true, true, false, true, true,
 'Organization verified ✓',
 'Congratulations! Your organization has been verified. You now have access to verified features.'),
('org_verification_rejected', 'compliance', true, true, false, true, true,
 'Verification unsuccessful',
 'Your verification request was not approved. Reason: {{reason}}. You can resubmit with updated information.'),
('org_policy_update_required', 'compliance', true, true, false, true, true,
 'Action required: Policy update',
 'Our {{policy_name}} has been updated. Please review and accept the changes by {{deadline}}.'),
-- System
('org_announcement', 'system', true, true, true, true, false,
 '{{announcement_title}}',
 '{{announcement_body}}'),
('org_maintenance_notice', 'system', true, true, true, true, true,
 'Scheduled maintenance',
 'Gonasi will be undergoing maintenance on {{maintenance_date}} from {{start_time}} to {{end_time}}. Some features may be unavailable.');