import type { NewLiveSessionSchemaTypes } from '@gonasi/schemas/liveSessions';

import { getUserId } from '../auth';
import type { TypedSupabaseClient } from '../client';
import type { ApiResponse } from '../types';

export const createLiveSession = async ({
  supabase,
  data,
}: {
  supabase: TypedSupabaseClient;
  data: NewLiveSessionSchemaTypes;
}): Promise<ApiResponse<{ id: string; sessionCode: string }>> => {
  const userId = await getUserId(supabase);

  if (!userId) {
    return {
      success: false,
      message: 'User not authenticated.',
    };
  }

  try {
    // Validate user permissions before attempting insert
    const { data: roleData } = await supabase.rpc('get_user_org_role', {
      arg_org_id: data.organizationId,
      arg_user_id: userId,
    });

    if (!roleData || !['owner', 'admin', 'editor'].includes(roleData)) {
      return {
        success: false,
        message:
          'You do not have permission to create live sessions. Only organization owners, admins, and editors can create live sessions.',
      };
    }

    // Check organization tier
    const { data: tierData } = await supabase.rpc('get_org_tier', {
      p_org: data.organizationId,
    });

    if (tierData === 'temp') {
      return {
        success: false,
        message:
          'Your organization is on a temporary tier. Please upgrade your subscription to create live sessions.',
      };
    }

    // Create the live session
    // Note: session_code is auto-generated by the trigger_generate_session_code() trigger
    const { data: sessionData, error } = await supabase
      .from('live_sessions')
      .insert({
        name: data.name,
        description: data.description || null,
        organization_id: data.organizationId,
        created_by: userId,
        session_code: '', // Placeholder; will be auto-set by DB trigger, but required by types
        // session_code will be auto-generated by the database trigger
        visibility: data.visibility,
        session_key: data.sessionKey || null,
        session_type: data.sessionType,
        scheduled_start_time: data.scheduledStartTime || null,
        max_participants: data.maxParticipants || null,
        allow_late_join: data.allowLateJoin,
        show_leaderboard: data.showLeaderboard,
        enable_chat: data.enableChat,
        enable_reactions: data.enableReactions,
      })
      .select('id, session_code')
      .single();

    if (error || !sessionData) {
      console.error('[createLiveSession] error:', error);

      // Provide better error messages for common RLS violations
      if (error?.code === '42501') {
        return {
          success: false,
          message:
            'Permission denied. Please check your organization membership and subscription status.',
        };
      }

      return {
        success: false,
        message: error?.message || 'Failed to create live session.',
      };
    }

    return {
      success: true,
      message: 'Live session created successfully!',
      data: {
        id: sessionData.id,
        sessionCode: sessionData.session_code,
      },
    };
  } catch (err) {
    console.error('Unexpected error in createLiveSession:', err);
    return {
      success: false,
      message: 'Something went wrong—try again in a bit.',
    };
  }
};
