import type { EditorThemeClasses } from 'lexical';

const theme: EditorThemeClasses = {
  autocomplete: '',
  blockCursor: '',
  characterLimit: '',
  code: 'bg-muted px-2 py-1 rounded font-mono text-sm text-muted-foreground font-secondary',
  codeHighlight: {
    atrule: 'text-purple-500 font-secondary',
    attr: 'text-sky-600 font-secondary',
    boolean: 'text-amber-600 font-secondary',
    builtin: 'text-indigo-500 font-secondary',
    cdata: 'text-gray-400 italic font-secondary',
    char: 'text-indigo-400 font-secondary',
    class: 'text-emerald-500 font-secondary',
    'class-name': 'text-emerald-600 font-secondary',
    comment: 'text-gray-400 italic font-secondary',
    constant: 'text-pink-500 font-secondary',
    deleted: 'text-red-500 line-through font-secondary',
    doctype: 'text-gray-400 font-secondary',
    entity: 'text-cyan-500 font-secondary',
    function: 'text-green-600 font-secondary',
    important: 'text-red-600 font-bold font-secondary',
    inserted: 'text-green-500 font-secondary',
    keyword: 'text-purple-500 font-secondary',
    namespace: 'text-blue-500 font-secondary',
    number: 'text-orange-500 font-secondary',
    operator: 'text-pink-500 font-secondary',
    prolog: 'text-gray-400 font-secondary',
    property: 'text-orange-500 font-secondary',
    punctuation: 'text-muted-foreground font-secondary',
    regex: 'text-teal-500 font-secondary',
    selector: 'text-indigo-600 font-secondary',
    string: 'text-green-600 font-secondary',
    symbol: 'text-pink-500 font-secondary',
    tag: 'text-red-600 font-secondary',
    url: 'text-blue-600 underline font-secondary',
    variable: 'text-yellow-600 font-secondary',
  },
  embedBlock: {
    base: 'border rounded p-4 bg-muted font-secondary',
    focus: 'ring-2 ring-primary font-secondary',
  },
  hashtag: 'text-primary hover:underline font-secondary',
  heading: {
    h1: 'text-3xl font-bold mb-4 font-secondary',
    h2: 'text-2xl font-semibold mb-3 font-secondary',
    h3: 'text-xl font-semibold mb-2 font-secondary',
    h4: 'text-lg font-medium mb-2 font-secondary',
    h5: 'text-base font-medium mb-1 font-secondary',
    h6: 'text-sm font-medium mb-1 font-secondary',
  },
  hr: 'my-6 border-t border-muted font-secondary',
  hrSelected: 'my-6 border-t-2 border-primary font-secondary',
  image: 'my-4 rounded-md shadow font-secondary',
  indent: 'ml-4 font-secondary',
  inlineImage: 'inline-block align-middle rounded shadow-sm font-secondary',
  layoutContainer: 'grid grid-cols-1 gap-4 md:grid-cols-2 font-secondary',
  layoutItem: 'p-4 border rounded bg-background font-secondary',
  link: 'text-primary underline underline-offset-2 hover:text-primary/80 font-secondary',
  list: {
    checklist: 'list-none pl-0 font-secondary',
    listitem: 'mb-1 ml-4 list-disc font-secondary',
    listitemChecked: 'line-through text-muted-foreground font-secondary',
    listitemUnchecked: 'font-secondary',
    nested: {
      listitem: 'ml-6 list-circle font-secondary',
    },
    olDepth: [
      'ml-4 list-decimal font-secondary',
      'ml-6 list-decimal font-secondary',
      'ml-8 list-decimal font-secondary',
      'ml-10 list-decimal font-secondary',
      'ml-12 list-decimal font-secondary',
    ],
    ul: 'list-disc list-inside font-secondary',
  },
  ltr: 'text-left font-secondary',
  mark: 'bg-yellow-100 font-semibold font-secondary',
  markOverlap: 'bg-yellow-200 font-secondary',
  paragraph: 'mb-4 text-base leading-relaxed font-secondary',
  placeholder:
    'text-muted-foreground absolute top-[15px] left-[10px] text-sm pointer-events-none font-secondary',
  quote: 'border-l-4 border-muted pl-4 italic text-muted-foreground my-4 font-secondary',
  rtl: 'text-right font-secondary',
  specialText: 'text-purple-600 font-semibold font-secondary',
  tab: 'px-4 inline-block font-secondary',
  table: 'table-auto border-collapse w-full font-secondary',
  tableAddColumns: 'bg-muted hover:bg-accent cursor-pointer font-secondary',
  tableAddRows: 'bg-muted hover:bg-accent cursor-pointer font-secondary',
  tableAlignment: {
    center: 'text-center font-secondary',
    right: 'text-right font-secondary',
  },
  tableCell: 'border px-4 py-2 font-secondary',
  tableCellActionButton: 'text-sm text-muted-foreground hover:text-primary font-secondary',
  tableCellActionButtonContainer: 'flex gap-2 items-center font-secondary',
  tableCellHeader: 'bg-muted text-left font-bold px-4 py-2 font-secondary',
  tableCellResizer: 'w-1 cursor-col-resize bg-muted-foreground font-secondary',
  tableCellSelected: 'bg-primary/10 border-primary font-secondary',
  tableFrozenColumn: 'bg-muted-foreground/10 font-secondary',
  tableFrozenRow: 'bg-muted-foreground/10 font-secondary',
  tableRowStriping: 'odd:bg-muted/10 font-secondary',
  tableScrollableWrapper: 'overflow-x-auto font-secondary',
  tableSelected: 'bg-primary/5 font-secondary',
  tableSelection: 'bg-primary/10 font-secondary',
  text: {
    bold: 'font-bold font-secondary',
    capitalize: 'capitalize font-secondary',
    code: 'bg-muted px-1 rounded text-sm font-mono font-secondary',
    highlight: 'bg-yellow-100 font-secondary',
    italic: 'italic font-secondary',
    lowercase: 'lowercase font-secondary',
    strikethrough: 'line-through font-secondary',
    subscript: 'align-sub text-xs font-secondary',
    superscript: 'align-super text-xs font-secondary',
    underline: 'underline font-secondary',
    underlineStrikethrough: 'underline line-through font-secondary',
    uppercase: 'uppercase font-secondary',
  },
};

export default theme;
