export const ALL_PLUGINS = [
  {
    id: 'authoring_tools',
    name: 'Authoring Tools',
    description: 'Tools for content creation, formatting, and structuring',
    plugins: [
      {
        id: 'text_tools',
        name: 'Text Tools',
        description: 'Add and format rich text content',
        icon: 'Text',
        pluginTypes: [
          {
            id: 'rich_text_editor',
            name: 'Rich Text Editor',
            description: 'Add and format content with headings, styles, and links.',
            example: 'Make this sentence *italic* or **bold**.',
            icon: 'TextCursorInput',
            comingSoon: false,
          },
        ],
      },
    ],
  },
  {
    id: 'assessment',
    name: 'Assessment Tools',
    description: 'Tools for evaluating learner understanding',
    plugins: [
      {
        id: 'question_types',
        name: 'Question Types',
        description: 'Support for various types of quiz questions',
        icon: 'ListCheck',
        pluginTypes: [
          {
            id: 'true_false',
            name: 'True/False',
            description: 'Classic binary choice.',
            example: 'The Earth is flat.',
            icon: 'ToggleRight',
            comingSoon: false,
          },
          {
            id: 'single_choice',
            name: 'Single Choice',
            description: 'One correct answer, multiple options.',
            example: 'What is the capital of France?',
            icon: 'CircleDot',
            comingSoon: false,
          },
          {
            id: 'multiple_choice',
            name: 'Multiple Choice',
            description: 'More than one correct answer.',
            example: 'Which of the following are programming languages?',
            icon: 'SquareCheck',
            comingSoon: false,
          },
        ],
      },
      {
        id: 'interactive_questions',
        name: 'Interactive Questions',
        description: 'Use drag and drop to match, order, or categorize items',
        icon: 'SquareMousePointer',
        pluginTypes: [
          {
            id: 'match_pairs',
            name: 'Matching Pairs',
            description: 'Match concepts or words from one list to another.',
            example: 'Match the country to its capital.',
            icon: 'DragAndDropMatch',
            comingSoon: false,
          },
          {
            id: 'order_sequence',
            name: 'Order Sequence',
            description: 'Order items or events in a sequence.',
            example: 'Arrange the steps of a scientific method.',
            icon: 'DragAndDropSequence',
            comingSoon: true,
          },
          {
            id: 'item_categorization',
            name: 'Item Categorization',
            description: 'Categorize items into defined groups.',
            example: 'Sort animals into mammal, reptile, and bird.',
            icon: 'DragAndDropCategorize',
            comingSoon: true,
          },
        ],
      },
    ],
  },
  {
    id: 'visualization',
    name: 'Interactive Visualizations',
    description: 'Visual tools for data and concept exploration',
    plugins: [
      {
        id: 'chart_tools',
        name: 'Chart Tools',
        description: 'Create interactive charts and graphs',
        icon: 'BarChart4',
        pluginTypes: [
          {
            id: 'bar_chart',
            name: 'Bar Chart',
            description: 'Create bar charts to represent data visually.',
            example: 'Show population by country using a bar chart.',
            icon: 'BarChart',
            comingSoon: true,
          },
          {
            id: 'line_chart',
            name: 'Line Chart',
            description: 'Create line charts to visualize data trends.',
            example: 'Show temperature changes over time with a line chart.',
            icon: 'LineChart',
            comingSoon: true,
          },
          {
            id: 'pie_chart',
            name: 'Pie Chart',
            description: 'Create pie charts to represent data as parts of a whole.',
            example: 'Show market share distribution with a pie chart.',
            icon: 'PieChart',
            comingSoon: true,
          },
        ],
      },
      {
        id: 'timeline_tools',
        name: 'Timeline Tools',
        description: 'Explore concepts and events on a timeline',
        icon: 'ChartNoAxesGantt',
        pluginTypes: [
          {
            id: 'history_timeline',
            name: 'Historical Timeline',
            description: 'Explore and visualize historical events on a timeline.',
            example: 'Display key events from World War II on a timeline.',
            icon: 'TimelineHistorical',
            comingSoon: true,
          },
          {
            id: 'project_timeline',
            name: 'Project Timeline',
            description: 'Show project milestones and deadlines on a timeline.',
            example: 'Visualize project phases in a timeline format.',
            icon: 'TimelineProject',
            comingSoon: true,
          },
        ],
      },
    ],
  },
  {
    id: 'content_delivery',
    name: 'Content Delivery Tools',
    description: 'Tools for structuring and revealing content to learners',
    plugins: [
      {
        id: 'reveal_tools',
        name: 'Reveal Tools',
        description: 'Enable progressive content disclosure and hints',
        icon: 'Eye',
        pluginTypes: [
          {
            id: 'tap_reveal',
            name: 'Tap to Reveal',
            description: 'Reveal content when the learner taps on a hidden element.',
            example: 'Tap a card to reveal the answer underneath.',
            icon: 'MousePointerClick',
            comingSoon: false,
          },
          {
            id: 'step_reveal',
            name: 'Step-by-Step Reveal',
            description: 'Progressively reveal content in steps.',
            example: 'Show instructions in steps as the user progresses.',
            icon: 'ListOrdered',
            comingSoon: false,
          },
        ],
      },
      {
        id: 'media_tools',
        name: 'Media Tools',
        description: 'Use video, audio, and slides to enhance learning',
        icon: 'PlayCircle',
        pluginTypes: [
          {
            id: 'video_player',
            name: 'Video Player',
            description: 'Embed and play videos with interactive features.',
            example: 'Show a tutorial video with pause and play controls.',
            icon: 'VideoPlayer',
            comingSoon: true,
          },
          {
            id: 'audio_player',
            name: 'Audio Player',
            description: 'Embed and play audio lessons or podcasts.',
            example: 'Play an audio lesson on language learning.',
            icon: 'AudioPlayer',
            comingSoon: true,
          },
          {
            id: 'slideshow',
            name: 'Slideshow Viewer',
            description: 'Display slideshows with images and text.',
            example: 'Show a presentation in a slideshow format.',
            icon: 'SlideshowPlayer',
            comingSoon: true,
          },
        ],
      },
    ],
  },
  {
    id: 'simulation',
    name: 'Simulation Tools',
    description: 'Interactive simulations and modeling environments',
    plugins: [
      {
        id: 'physics_simulations',
        name: 'Physics Simulations',
        description: 'Simulate physical systems and experiments',
        icon: 'Atom',
        pluginTypes: [
          {
            id: 'motion_simulation',
            name: 'Motion Simulation',
            description: 'Simulate the motion of objects in different environments.',
            example: 'Simulate the motion of a pendulum.',
            icon: 'MotionSimulation',
            comingSoon: true,
          },
          {
            id: 'gravity_simulation',
            name: 'Gravity Simulation',
            description: 'Simulate the effects of gravity on different objects.',
            example: 'Simulate an object falling under gravity.',
            icon: 'GravitySimulation',
            comingSoon: true,
          },
        ],
      },
    ],
  },
] as const;
